# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         CGI-Application-Plugin-Mason
version:      1.01
version_from: lib/CGI/Application/Plugin/Mason.pm
installdirs:  site
requires:
    CGI::Application:              4.05
    CGI::Application::Plugin::Stash: 0.01
    HTML::Mason:                   1.35

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
